name: PostgreSQL Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test_laravel
        ports:
          - 55432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        php-versions: ['8.2']
        laravel: ['11.*']

    name: PostgreSQL Tests - PHP ${{ matrix.php-versions }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest

      - name: Run PHPUnit Tests
        env:
          DB_CONNECTION: pgsql
          DB_DATABASE: db_test_laravel
          DB_HOST: localhost
          DB_PORT: 55432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: vendor/bin/phpunit --testdox
