name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: atec123
        options: >-
          --health-cmd="pg_isready -U ${{ job.services.postgres.env.POSTGRES_USER }}" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Setup Database
      run: |
        php -r "file_put_contents('.env', str_replace('DB_CONNECTION=mysql', 'DB_CONNECTION=pgsql', file_get_contents('.env')));"
        php -r "file_put_contents('.env', str_replace('DB_HOST=127.0.0.1', 'DB_HOST=127.0.0.1', file_get_contents('.env')));"
        php -r "file_put_contents('.env', str_replace('DB_PORT=3306', 'DB_PORT=5432', file_get_contents('.env')));"
        php -r "file_put_contents('.env', str_replace('DB_DATABASE=laravel', 'DB_DATABASE=laravel', file_get_contents('.env')));"
        php -r "file_put_contents('.env', str_replace('DB_USERNAME=root', 'DB_USERNAME=laravel', file_get_contents('.env')));"
        php -r "file_put_contents('.env', str_replace('DB_PASSWORD=', 'DB_PASSWORD=atec123', file_get_contents('.env')));"
    - name: Run Migrations
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: atec123
      run: php artisan test
