name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --no-progress --no-scripts

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Serve Application
      run: php artisan serve --host=127.0.0.1 --port=8000 &

#    - name: Run Tests
#      run: php artisan test

  update-personal-branches:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Git Identity
      run: |
        git config --global user.email "bruno.silva.t0126205@edu.atec.pt"
        git config --global user.name "brunofilipefs96"

    - name: Fetch All Branches
      run: git fetch --all

    - name: Update Personal Branches
      run: |
        branches=("nelson" "rodrigo" "Melquisedeque")
        for branch in "${branches[@]}"
        do
          git checkout $branch && git pull origin $branch && git rebase origin/main && git push origin $branch --force
        done

        
# name: Run PHPUnit Tests

# on:
#   #push:
#     #branches:
#       #- main
#   #pull_request:
#     #branches:
#       #- main
#   workflow_dispatch: # Permite a execução manual

# jobs:
#   laravel-tests:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:latest
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: db_test_laravel
#         ports:
#           - 55432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Set up PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: 8.2

#       - name: Install Composer dependencies
#         run: |
#           composer install --no-interaction --no-progress --no-suggest

#       - name: Grant execute permission to PHPUnit
#         run: chmod +x vendor/bin/phpunit

#       - name: Run PHPUnit Tests
#         env:
#           DB_CONNECTION: pgsql
#           DB_DATABASE: db_test_laravel
#           DB_HOST: localhost
#           DB_PORT: 55432
#           DB_USERNAME: postgres
#           DB_PASSWORD: postgres
#         run: vendor/bin/phpunit --testdox
